### ISSUE TITLE
Autoload Issue

### ISSUE THREAD

**Issue by gponimansky** [Voidustries/Poly#2]
The GUI isn't loading the XML variables through a resource bundle properly.

**Comment by StoneMonarch** [comment]
Solved with: bb95354

**Comment by gponimansky** [comment]
Issue has not been solved since commit: 7faabdc

Issue still exists possible problem within how the settings.properties file is saved.

**Comment by StoneMonarch** [comment]
Database listing and active downloads were not ment to be part of the load process, rather to be set later after a query to the database.

Issue closed with commit: c75509c
